version: 0.2
env:
  variables:
    #Authentiaction server primary domain
    AUTH_DOMAIN: http://localhost:8000
    STACK_ID: local
    #Auth api link


    #The default identity and secret to generate tokens whenever an authentication needed by passing a token
    AUTH_DATASET_ID: -1
    AUTH_IDENTITY: volcanic
    AUTH_SECRET: volcanic!123
    #AUTH_DEFAULT_AUDIENCE: '["volcanic"]'


    #enable the caching service
    ENABLE_CACHING: false

    #shuts down the API HTTP mocking
    NOCK_OFF: false
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm i -g mocha
      - npm i -g eslint
  pre_build:
    commands:
      - echo "using environment $NODE_ENV"
      - npm install
      - npm run lint
      - npm test

