version: 0.2
env:
  variables:
    #Authentiaction server primary domain
    AUTH_DOMAIN: http://localhost:8000
    #Auth api link
    V1_API: /api/v1

    #The the default memory caching expiry time for internal Authentiaction token
    MODULE_TOKEN_DURATION: 60

    #The third party tokens generated memory caching expiry time
    THIRD_PARTY_TOKEN_DURATION: 60

    #The default identity and secret to generate tokens whenever an authentication needed by passing a token
    AUTH_DATASET_ID: -1
    AUTH_IDENTITY: volcanic
    AUTH_SECRET: volcanic!123
    AUTH_DEFAULT_AUDIENCE: '["volcanic"]'
    PRINCIPAL_ID: 1

    #enable the logging function
    ENABLE_LOGGIN: boolean

    #enable the caching service
    ENABLE_CACHING: boolean

    #Auth will validate the token on each request
    SERVER_TOKEN_VALIDATION: false

    #shuts down the API HTTP mocking
    NOCK_OFF: false
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm i -g mocha
      - npm i -g eslint
  pre_build:
    commands:
      - echo "using environment $NODE_ENV"
      - npm install
      - npm run lint
      - npm test

